
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dasha
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_course_development_copy


test:
  <<: *default
  database: rails_course_test_copy


